---
title: "Project Report"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    code_folding: hide
---

<style type="text/css">

h1.title {
  text-align: center;
}

</style>

## Motivation

* Healthy People 2020 identified housing instability as a key issue in addressing social determinants of health in the United States. 
* Evictions are an important element of housing instability, and approximately 2 million tenants were evicted nationwide in 2016.  



## Questions

* How have eviction rates changed over time by census tract in Brooklyn?
* Are there spatial patterns in the discrepancy between eviction filings and evictions at the neighborhood level? Do these patterns reflect distributions of other key variables of interest? 
* What factors are associated with eviction rates across census tract in Brooklyn?


## Data

### *Sources*

* Primary data source: [Eviction Lab](https://evictionlab.org/) 

* For gentrification measures: [Mapping Displacement and Gentrification in the New York Metropolitan Area (Urban Displacement Project)](https://www.urbandisplacement.org/maps/ny)

* For English language usage and population density: [American FactFinder](https://factfinder.census.gov/faces/nav/jsf/pages/guided_search.xhtml)

* Supplemental data source: [NYC Open Data](https://www1.nyc.gov/site/planning/data-maps/open-data/dwn-nynta.page)

Include links to shapefiles?

### *Cleaning*

After choosing to focus on New York City, data were limited to Brooklyn as this was the only borough with complete data for all time points from 2000 to 2016. 

Eviction rates and eviction filing rates represent the number of evictions or eviction filings divided by the number of renter occupied households in the census tract or neighborhood. 

To look at neighborhood-level data, sample weights were calculated by dividing the population of the census tract by the population of the neighborhood. These weights were then applied to all variables of interest to calculate aggregate measures by neighborhood.
```{r eval = FALSE}
neighborhood_data_prep = eviction_data %>% 
  group_by(neighborhood) %>% 
  mutate(
    neighb_pop = sum(population),
    tract_weight = population/neighb_pop,
    eviction_discrepancy = eviction_filing_rate - eviction_rate,
    weighted_eviction_discrep = eviction_discrepancy*tract_weight,
    weighted_eviction_rate = eviction_rate*tract_weight,
    pct_nonwhite = 100 - pct_white,
    weighted_pct_nonwhite = pct_nonwhite*tract_weight,
    weighted_povertyrate = poverty_rate*tract_weight)

neighborhood_data = neighborhood_data_prep %>% 
  summarize(
    wt_eviction_rate = round(as.numeric(sum(weighted_eviction_rate)), digits = 2),
    wt_eviction_rate_discrep = round(sum(weighted_eviction_discrep), digits = 2),
    wt_pct_nonwhite = sum(weighted_pct_nonwhite),
    wt_povertyrate = sum(weighted_povertyrate)) %>% 
  ungroup() %>% 
  mutate(neighborhood = as.factor(neighborhood))
```


### *Variables of interest*

NOTE: Eviction rate and eviction filing rate represent the number of evictions or eviction filings divided by the number of renter occupied households and multiplied by 100 to be interpreted as a percentage. 

## Methods



## Exploratory Analysis

## Additional Analysis

## Discussion